- build.sh
- src/CogniteSdk.fsproj
- src/sequences/CreateSequences.fs
- src/sequences/DeleteRows.fs
- src/sequences/DeleteSequences.fs
- src/sequences/Edm.fs
- src/sequences/InsertRows.fs
- src/sequences/Json.fs
- src/sequences/ListSequences.fs
- src/sequences/Model.fs
- src/sequences/RetrieveRows.fs
- src/sequences/RetrieveSequences.fs
- src/sequences/SearchSequences.fs
- src/sequences/UpdateSequences.fs
- test/integration/csharp/Sequences.cs
- test/integration/fsharp/Sequences.fs
Add C# SDK for Insert and Delete Rows
- Refactor and split rows handling into separate files.
- Split CLR (C#) model into Edm.fs
- Add integration test for insert and delete of rows
> Add C# SDK for Insert and Delete Rows

- src/sequences/Json.fs
- src/sequences/Model.fs
- test/integration/fsharp/Sequences.fs
- Reduce the number of types. Share ValueType enum between C# and F#.
> Remove ColumnType

- src/assets/ListAssets.fs
- src/events/ListEvents.fs
- src/files/ListFiles.fs
- src/raw/Model.fs
- src/sequences/Edm.fs
- src/sequences/ListSequences.fs
Let CDF decide what the limits are and provide the correct error message. Fixes #33 .
> Remove all limits.

- CogniteSdk.Types/Assets/AggregateResult.cs
- CogniteSdk.Types/Assets/AssetReadDto.cs
- CogniteSdk.Types/DataPoints/DataPointsLatestQueryDto.cs
- CogniteSdk.Types/Timeseries/TimeSeriesQueryDto.cs
- CogniteSdk/src/Client.cs
- CogniteSdk/src/Resources/Assets.cs
- CogniteSdk/src/Resources/DataPoints.cs
- CogniteSdk/src/Resources/Events.cs
- CogniteSdk/src/Resources/Sequences.cs
- CogniteSdk/src/Resources/TimeSeries.cs
- CogniteSdk/test/fsharp/DataPoints.fs
- CogniteSdk/test/fsharp/Sequences.fs
- CogniteSdk/test/fsharp/TimeSeries.fs
- Oryx.Cognite/src/DataPoints.fs
- Oryx.Cognite/src/TimeSeries.fs
- credentials.sh
- Rename to DTO's so we explicitly say that these are transfer and not domain types
> Rename types to DTO

- CogniteSdk.Types/Assets/AssetReadDto.cs
- CogniteSdk.Types/Files/FileReadDto.cs
- CogniteSdk.Types/Sequences/SequenceReadDto.cs
- CogniteSdk.Types/Sequences/SequenceWriteDto.cs
- CogniteSdk/test/fsharp/Assets.fs
- CogniteSdk/test/fsharp/Files.fs
- README.md
- System.Text.Json currently only support Dictionary.
> Rewrite from IDictionary to Dictionary

- CogniteSdk.Types/Common/Converters.cs
- CogniteSdk.Types/Common/ResponseError.cs
- CogniteSdk.Types/Common/ResponseException.cs
- CogniteSdk.Types/Login/LoginDataReadDto.cs
- CogniteSdk.Types/Login/LoginStatusReadDto.cs
- CogniteSdk/src/Client.cs
- CogniteSdk/src/Resources/Login.cs
- CogniteSdk/test/fsharp/CogniteSdk.Test.fsproj
- CogniteSdk/test/fsharp/Login.fs
- Oryx.Cognite/src/Common.fs
- Oryx.Cognite/src/Handler.fs
- Oryx.Cognite/src/Login.fs
- Oryx.Cognite/src/Oryx.Cognite.fsproj
- Add support for login status.
- Fix types for error responses. Should be MultiValue instead of ValueType.
- Add integration test for login status.
> Add login (partial)

- CogniteSdk.Types/DataPoints/DataPointsLatestQueryDto.cs
- CogniteSdk/test/fsharp/DataPoints.fs
Did this by extending the Identity class.
> Fix Id in IdentityWithBefore to be nullable

- CogniteSdk.Types/Events/EventSearchDto.cs
- CogniteSdk/test/fsharp/Events.fs
Events support search only on description.
> Event search only on description

- CogniteSdk.Types/DataPoints/DataPointsReadDto.cs
- CogniteSdk/src/Resources/DataPoints.cs
- CogniteSdk/src/paket.references
- CogniteSdk/test/fsharp/DataPoints.fs
- Oryx.Cognite/src/DataPoints.fs
- Oryx.Cognite/src/Handler.fs
- Oryx.Cognite/src/paket.references
- paket.dependencies
- paket.lock
- Also remove unused dependency.
> Fix return type for aggregates

- CogniteSdk.Types/Common/Stringable.cs
- CogniteSdk/src/Client.cs
- paket.lock
Fix stringable indenting
- Update Oryx
> Fix stringable indenting

- CogniteSdk.Types/Assets/AssetFilterDto.cs
- CogniteSdk.Types/Events/EventUpdateDto.cs
- CogniteSdk.Types/Files/FileUpdateDto.cs
- CogniteSdk.Types/Sequences/SequenceUpdateDto.cs
- CogniteSdk.Types/Timeseries/TimeSeriesUpdateDto.cs
Fix datasetId updates 
- Needs to be Identity object instead of long: https://pr-461.specs.preview.cogniteapp.com/v1.json.html#operation/listAssets
> Fix datasetId updates

- CogniteSdk.Types/Common/Stringable.cs
- CogniteSdk.Types/Relationships/RelationshipFilterDto.cs
- CogniteSdk.Types/Relationships/RelationshipLabelDto.cs
- CogniteSdk.Types/Relationships/RelationshipQueryDto.cs
- CogniteSdk.Types/Relationships/RelationshipReadDto.cs
- CogniteSdk.Types/Relationships/RelationshipResource.cs
- CogniteSdk.Types/Relationships/RelationshipVertexProperty.cs
- CogniteSdk.Types/Relationships/RelationshipWriteDto.cs
- CogniteSdk.Types/Relationships/RestrictedGraphQueryDto.cs
- CogniteSdk.Types/Relationships/RestrictedGraphQueryResultDto.cs
- CogniteSdk/src/Client.cs
- CogniteSdk/src/Resources/Playground.cs
- CogniteSdk/src/Resources/Relationships.cs
- CogniteSdk/test/fsharp/Relationships.fs
- Use system newline for the stringable handling
- Add missing file headers.
> Scope Relationships under Playground property of the client

- CogniteSdk.Types/Relationships/Relationship.cs
- CogniteSdk.Types/Relationships/RelationshipCreate.cs
- CogniteSdk.Types/Relationships/RelationshipFilter.cs
- CogniteSdk.Types/Relationships/RelationshipLabel.cs
- CogniteSdk.Types/Relationships/RelationshipQuery.cs
- CogniteSdk.Types/Relationships/RelationshipResource.cs
- CogniteSdk.Types/Relationships/RelationshipVertexProperty.cs
- CogniteSdk.Types/Relationships/RestrictedGraphQuery.cs
- CogniteSdk.Types/Relationships/RestrictedGraphQueryResult.cs
- CogniteSdk/src/Resources/Relationships.cs
- CogniteSdk/test/fsharp/Relationships.fs
- Oryx.Cognite/src/Relationships.fs
Move relationships to the common namespace, and fix naming.
> Refactor relationships

- CogniteSdk.Types/Sequences/Rows/SequenceData.cs
- CogniteSdk.Types/Sequences/Rows/SequenceDataCreate.cs
- CogniteSdk.Types/Sequences/Rows/SequenceRow.cs
- CogniteSdk.Types/Sequences/Rows/SequenceRowDelete.cs
- CogniteSdk.Types/Sequences/Rows/SequenceRowQuery.cs
- CogniteSdk/src/Client.cs
- CogniteSdk/src/Resources/Sequences.cs
- CogniteSdk/test/csharp/Sequences.cs
- CogniteSdk/test/fsharp/Sequences.fs
- Oryx.Cognite/src/Common.fs
- Oryx.Cognite/src/Sequences.fs
- playground/fsharp/Program.fs
Rename sequence types and adjust namespaces.
> Rename sequence types

- CogniteSdk.Types/Raw/RawRowCreateJson.cs
- CogniteSdk/src/Resources/Raw.cs
- CogniteSdk/test/fsharp/Assets.fs
- CogniteSdk/test/fsharp/Files.fs
- CogniteSdk/test/fsharp/Raw.fs
- Oryx.Cognite/src/Raw.fs
Add a new extension method on Raw CreateRow where columns are just a JsonElement.
> Change raw create to use JsonElement directly

- CogniteSdk.Types/Assets/AssetFilter.cs
- CogniteSdk.Types/Common/LabelFilter.cs
- CogniteSdk.Types/Common/Update.cs
- CogniteSdk/test/csharp/Assets.cs
- CogniteSdk/test/fsharp/Assets.fs
* Label filtering should now conform to changed API
> Rewrite label filtering [CDF-7434]

- CogniteSdk.Types/Common/LabelFilter.cs
- CogniteSdk/test/fsharp/Assets.fs
- CogniteSdk/test/fsharp/TimeSeries.fs
- Oryx.Cognite/src/Assets.fs
- Oryx.Cognite/src/Events.fs
- Oryx.Cognite/src/Files.fs
- Oryx.Cognite/src/Playground/Functions.fs
- Oryx.Cognite/src/Playground/Relationships.fs
- Oryx.Cognite/src/TimeSeries.fs
- Remove obsolete `Contains` property
- Make it possible to create filters directly from sequences of strings
- Cleanup code
- Sort usings
- Fix tests
> Make it easier to use labels

- .github/workflows/publish.yml
- CogniteSdk/test/fsharp/Events.fs
- Oryx.Cognite/src/Common.fs
what's missing:
`AssemblyVersion` needs to be equal M.0.0.0 where M is a major version number, now it's just 1.0.0.0
> Add assembly file version to x-cdp-sdk header

- Oryx.Cognite/src/Handler.fs
- Oryx.Cognite/src/Login.fs
- Oryx.Cognite/src/Playground/Handler.fs
- README.md
- paket.dependencies
- paket.lock
- Fix logging by moving log operator last in chain
- Update README.
> Stable Oryx v3

- .github/workflows/build-and-test.yml
- CogniteSdk/test/csharp/TestBase.cs
- CogniteSdk/test/fsharp/Common.fs
- README.md
- test.sh
- test_auth.sh
can someone check how this behaves on windows?
> Add AAD token auth for greenfield tests

- CogniteSdk.Types/Sequences/SequenceColumnWrite.cs
- CogniteSdk/test/fsharp/Sequences.fs
The API gives us an error, as the SDK sends "metaData". Added to test to confirm that this solves the issue.
> Change MetaData to Metadata in sequence columns

- CogniteSdk.Types/Sequences/Rows/SequenceRowQuery.cs
- CogniteSdk/test/csharp/Sequences.cs
> Fix columns parameter on list sequence rows

- CogniteSdk.Types/ExtPipes/ExtPipe.cs
- CogniteSdk.Types/ExtPipes/ExtPipeContact.cs
- CogniteSdk.Types/ExtPipes/ExtPipeCreate.cs
- CogniteSdk.Types/ExtPipes/ExtPipeDelete.cs
- CogniteSdk.Types/ExtPipes/ExtPipeFilter.cs
- CogniteSdk.Types/ExtPipes/ExtPipeQuery.cs
- CogniteSdk.Types/ExtPipes/ExtPipeRawTable.cs
- CogniteSdk.Types/ExtPipes/ExtPipeUpdate.cs
- CogniteSdk.Types/ExtPipes/Runs/ExtPipeRun.cs
- CogniteSdk.Types/ExtPipes/Runs/ExtPipeRunCreate.cs
- CogniteSdk.Types/ExtPipes/Runs/ExtPipeRunFilter.cs
- CogniteSdk.Types/ExtPipes/Runs/ExtPipeRunQuery.cs
- CogniteSdk/src/Client.cs
- CogniteSdk/src/Resources/ExtPipes.cs
- CogniteSdk/test/csharp/ExtPipes.cs
- CogniteSdk/test/csharp/TestBase.cs
- Oryx.Cognite/src/ExtPipes.fs
- Oryx.Cognite/src/Oryx.Cognite.fsproj
New API feature for monitoring extractors and other data pipelines. The feature is publicly available in the API, and should go fully live by the end of this month.
> Extraction pipelines

- CogniteSdk.Types/Files/FileCreate.cs
Adding documented variables to files upload
> Adding SecurityCategories to File Upload

- CogniteSdk.Types/Labels/Label.cs
- CogniteSdk.Types/Labels/LabelCreate.cs
- CogniteSdk.Types/Labels/LabelDelete.cs
- CogniteSdk.Types/Labels/LabelListFilter.cs
- CogniteSdk.Types/Labels/LabelQuery.cs
- CogniteSdk/src/Client.cs
- CogniteSdk/src/Resources/Labels.cs
- CogniteSdk/test/fsharp/CogniteSdk.Test.fsproj
- CogniteSdk/test/fsharp/Labels.fs
- Oryx.Cognite/src/Labels.fs
- Oryx.Cognite/src/Oryx.Cognite.fsproj
Support for creating, listing and deleting label definitions.
> Labels support

- paket.lock
> Use Oryx beta 001

- CogniteSdk/src/Resources/ExtPipes.cs
- CogniteSdk/src/Resources/Labels.cs
- CogniteSdk/src/Resources/Login.cs
- CogniteSdk/src/Resources/Raw.cs
- CogniteSdk/src/Resources/Resource.cs
Using _ctx only works if there is no authenticator.
This also makes _ctx private, to ensure that this issue is not repeated.
> Use GetContext over _ctx

- README.md
- paket.lock
Say that SDK is unofficial instead of "not recommended ..."
> Change README

- CogniteSdk.Types/Common/ResponseError.cs
- CogniteSdk.Types/ExtPipes/Configs/CreateExtPipeConfig.cs
- CogniteSdk.Types/ExtPipes/Configs/ExtPipeConfig.cs
- CogniteSdk.Types/ExtPipes/Configs/ExtPipeConfigCreate.cs
- CogniteSdk.Types/ExtPipes/Configs/GetConfigQuery.cs
- CogniteSdk.Types/ExtPipes/Configs/ListConfigQuery.cs
- CogniteSdk.Types/ExtPipes/Configs/RevertConfigRequest.cs
- CogniteSdk/src/Resources/Playground.cs
- CogniteSdk/src/Resources/Playground/ExtPipeConfigs.cs
- CogniteSdk/test/csharp/ExtPipes.cs
- CogniteSdk/test/csharp/TestBase.cs
- Oryx.Cognite/src/ExtPipes.fs
- Oryx.Cognite/src/Handler.fs
Playground API for extraction configuration files.
> Extraction configs

- CogniteSdk.Types/Annotations/Annotation.cs
- CogniteSdk.Types/Annotations/AnnotationCommon.cs
- CogniteSdk.Types/Annotations/AnnotationCreate.cs
- CogniteSdk.Types/Annotations/AnnotationData.cs
- CogniteSdk.Types/Annotations/AnnotationDelete.cs
- CogniteSdk.Types/Annotations/AnnotationFilter.cs
- CogniteSdk.Types/Annotations/AnnotationQuery.cs
- CogniteSdk.Types/Annotations/AnnotationSuggest.cs
- CogniteSdk.Types/Annotations/AnnotationUpdate.cs
- CogniteSdk/src/Resources/Playground.cs
- CogniteSdk/src/Resources/Playground/Annotations.cs
- CogniteSdk/test/csharp/Annotations.cs
- CogniteSdk/test/csharp/TestBase.cs
- Oryx.Cognite/src/Oryx.Cognite.fsproj
- Oryx.Cognite/src/Playground/Annotations.fs
- Oryx.Cognite/src/Playground/Handler.fs
This PR introduces the support for annotations with boundingVolume. It is needed for internal use.
> [BND3D-1388] Add annotations support

- CogniteSdk.Types/Beta/DataModels/Edges/BaseEdge.cs
- CogniteSdk.Types/Beta/DataModels/Edges/EdgeIngestRequest.cs
- CogniteSdk.Types/Beta/DataModels/Edges/EdgeListResponse.cs
- CogniteSdk.Types/Beta/DataModels/Filter.cs
- CogniteSdk.Types/Beta/DataModels/ModelIdentifier.cs
- CogniteSdk.Types/Beta/DataModels/Models/ItemsWithSpaceExternalId.cs
- CogniteSdk.Types/Beta/DataModels/Models/ListModelsQuery.cs
- CogniteSdk.Types/Beta/DataModels/Models/Model.cs
- CogniteSdk.Types/Beta/DataModels/Models/ModelConstraints.cs
- CogniteSdk.Types/Beta/DataModels/Models/ModelIndexes.cs
- CogniteSdk.Types/Beta/DataModels/Nodes/BaseNode.cs
- CogniteSdk.Types/Beta/DataModels/Nodes/NodeFilterQuery.cs
- CogniteSdk.Types/Beta/DataModels/Nodes/NodeIngestRequest.cs
- CogniteSdk.Types/Beta/DataModels/Nodes/NodeListResponse.cs
- CogniteSdk.Types/Beta/DataModels/Nodes/RetrieveNodesRequest.cs
- CogniteSdk.Types/Beta/DataModels/PropertySort.cs
- CogniteSdk.Types/Beta/DataModels/Query.cs
- CogniteSdk.Types/Beta/DataModels/Space.cs
- CogniteSdk.Types/Common/ResponseError.cs
- CogniteSdk.Types/Common/ResponseException.cs
- CogniteSdk/src/Resources/Beta.cs
- CogniteSdk/src/Resources/Beta/DataModels.cs
- CogniteSdk/test/csharp/DataModels.cs
- CogniteSdk/test/csharp/TestBase.cs
- CogniteSdk/test/fsharp/Files.fs
- Oryx.Cognite/src/Beta/DataModels.fs
- Oryx.Cognite/src/Beta/Handler.fs
- Oryx.Cognite/src/Common.fs
- Oryx.Cognite/src/Oryx.Cognite.fsproj
Beta implementation of the DMS API. Needed for some exploratory extractor work.
This API is likely to be quite important, so I put some extra effort into making it convenient to use, requiring a few custom converters.
The docs that exist are not quite exhaustive, and slightly wrong in a few places, so some of this is based on reverse engineering of code from the ark repo, and a bit of exploration, this is covered by the tests.
I think it is likely that parts of the API will change in the future.
> Data model storage

- CogniteSdk.Types/Beta/DataModels/Views/ViewCreate.cs
- CogniteSdk/test/csharp/DataModels.cs
Without this, it's not possible to add connections to views
> Use the ICreateViewProperty interface for view creation

- CogniteSdk.Types/Beta/Subscriptions/ListSubscriptionData.cs
- CogniteSdk.Types/Beta/Subscriptions/ListSubscriptionMembers.cs
- CogniteSdk.Types/Beta/Subscriptions/Subscription.cs
- CogniteSdk.Types/Beta/Subscriptions/SubscriptionCreate.cs
- CogniteSdk.Types/Beta/Subscriptions/SubscriptionDataResponse.cs
- CogniteSdk.Types/Beta/Subscriptions/SubscriptionUpdate.cs
- CogniteSdk/src/Resources/Beta.cs
- CogniteSdk/src/Resources/Beta/Subscriptions.cs
- CogniteSdk/test/csharp/DataModels.cs
- CogniteSdk/test/csharp/Subscriptions.cs
- CogniteSdk/test/csharp/TestBase.cs
- CogniteSdk/test/csharp/Transformations.cs
- Oryx.Cognite/src/Beta/DataModels.fs
- Oryx.Cognite/src/Beta/Handler.fs
- Oryx.Cognite/src/Beta/Subscriptions.fs
- Oryx.Cognite/src/Oryx.Cognite.fsproj
Support for the new timeseries subscription API.
> Timeseries subscriptions

- .github/workflows/publish.yml
Hopefully this time it will work...
> Fix publish trigger

- CogniteSdk.Types/DataPoints/DataPoint.cs
- CogniteSdk.Types/DataPoints/StatusCode.cs
- CogniteSdk/test/csharp/StatusCodes.cs
- Oryx.Cognite/src/Common.fs
This makes sense to include in the SDK. Complex tooling for working with status codes. Based on the OPC-UA standard and on the time series API.
> Port status codes from .NET utils

- renovate.json
the config lacks Cognite default settings, e.g. "do not rebase unless conficted", etc.
Need to align it with inretnal best practices
> chore: update renovate.json to use Cognite defaults
