cognitedata/cognite-sdk-dotnet

CogniteSdk.Types/Events/Event.cs
CogniteSdk/src/Client.cs
CogniteSdk/src/Resources/Assets.cs
CogniteSdk/src/Resources/DataPoints.cs
CogniteSdk/src/Resources/Events.cs
CogniteSdk/src/Resources/Files.cs
CogniteSdk/src/Resources/Login.cs
CogniteSdk/src/Resources/Playground.cs
CogniteSdk/src/Resources/Raw.cs
CogniteSdk/src/Resources/Relationships.cs
CogniteSdk/src/Resources/Resource.cs
CogniteSdk/src/Resources/Sequences.cs
CogniteSdk/src/Resources/TimeSeries.cs
CogniteSdk/test/fsharp/Events.fs
CogniteSdk/test/fsharp/Raw.fs
Oryx.Cognite/src/Common.fs
Oryx.Cognite/src/Handler.fs
paket.lock

Add `SetTokenProvider` method to client for getting a new bearer toke without building a new client.
- Add null checks to client methods
- Add resource abstract class to hide some boilerplate code for resource methods.
Not sure how to test, but once Oryx PR is approved we depend on the `authorize` function there which is unit-tested.
Will consider rewriting the client to nullable reference types some other time.

[DT-1442] Add method for setting bearer token for client.

---

CogniteSdk/src/Resources/Resource.cs
Oryx.Cognite/src/Handler.fs
paket.lock

This changes the semantics of the SDK to fail the request if any errors occurs while authenticating / refreshing the token which is the right thing to do. Thus we do this as a bug fix (missing error) and not as a breaking change for the SDK.

Use withTokenRenewer instead of withTokenProvider.

---

CogniteSdk.Types/Common/Update.cs
CogniteSdk/test/fsharp/TimeSeries.fs

Make `remove` required parameter for `DictionaryUpdate` to make sure we don't confuse it with `set` that have the same signature if only `add` is used and `remove` is default.
Also fix integration test to be more robust.

Make remove required parameter

---

CogniteSdk.Types/Assets/Asset.cs
CogniteSdk.Types/Assets/AssetCreate.cs
CogniteSdk.Types/Assets/AssetFilter.cs
CogniteSdk.Types/Assets/AssetUpdate.cs
CogniteSdk.Types/Common/ExternalId.cs
CogniteSdk.Types/Common/LabelFilter.cs
CogniteSdk.Types/Common/Update.cs

The obsolete flags generate compile warnings, which is more an annoyance than it is useful. Added "Currently only for use in playground" to the description of the same attributes where the obsolete flag were removed.

Remove obsolete flags from label defs [CDF-7453]

---

CogniteSdk.Types/Timeseries/TimeSeriesFilter.cs

I got `filter.externalAssetIds - did you mean rootAssetIds?` from CDF using the SDK.
https://docs.cognite.com/api/v1/#operation/listTimeSeries

Change ExternalAssetIds to AssetExternalIds on AssetFilter

---

CogniteSdk/src/Resources/Sequences.cs
CogniteSdk/test/fsharp/3DModels.fs
Oryx.Cognite/src/Sequences.fs

Sequence create currently returns SequenceData objects, which is supposed to be the return type for sequence row create requests. The return from sequence create is better suited to Sequence objects.

Fix return type of sequence create

---

CogniteSdk.Types/Common/Identity.cs

This is a pretty common use case, and passing around comparers is bothersome and error-prone.
We have dictionaries with Identities fairly frequently in the .NET utils, and thus far we've been using an IEqualityComparer, but that sometimes requires the user to be aware of this internal detail, and in general just causes avoidable issues.

Make Identity equality comparable

---

CogniteSdk/src/Resources/DataPoints.cs
CogniteSdk/test/fsharp/DataPoints.fs
Oryx.Cognite/src/DataPoints.fs
Oryx.Cognite/src/GZip.fs
Oryx.Cognite/src/Handler.fs
Oryx.Cognite/src/Oryx.Cognite.fsproj
playground/csharp/Program.cs

GZip support when writing datapoints. It is a separate method with a "CompressionLevel" parameter.
The simple code used for testing performance improvements is added to the C# playground project. The cutoff is around 10k numeric datapoints, the number would be different and more difficult to pin down for string datapoints. At the maximum chunk size of 100k datapoints the response time is improved 2-3 times.

Gzip datapoints support

---

CogniteSdk.Types/3D/3DModelUpdate.cs

Missed adding update fields to sdk according to documentation
https://docs.cognite.com/api/v1/#operation/update3DModels

Add DataSet ID to 3D Model update

---

CogniteSdk.Types/Groups/Acls.cs
CogniteSdk.Types/Groups/Group.cs
CogniteSdk.Types/Groups/GroupCreate.cs
CogniteSdk.Types/Groups/GroupDelete.cs
CogniteSdk.Types/Groups/GroupQuery.cs
CogniteSdk.Types/Token/TokenInspect.cs
CogniteSdk/src/Client.cs
CogniteSdk/src/Resources/Groups.cs
CogniteSdk/test/fsharp/CogniteSdk.Test.fsproj
CogniteSdk/test/fsharp/Common.fs
CogniteSdk/test/fsharp/Groups.fs
Oryx.Cognite/src/Common.fs
Oryx.Cognite/src/Groups.fs
Oryx.Cognite/src/Oryx.Cognite.fsproj
Oryx.Cognite/src/Token.fs

Suggested implementation for supporting groups. I've been looking into this because I'd like to list capabilities in token/inspect. A custom converter is necessary no matter what for properly serializing and deserializing capabilities. In order to make the user interface pleasant, and not plagued by complicated nested objects, I've made a custom converter which takes takes objects on the form
```
class SpecificCapability {
IEnumerable<string> Actions
ScopeType1 SomeScope
ScopeType2 SomeOtherScope
}
```
and converts them to
```
{
"specificCapability": {
"actions": [...],
"scope": {
"someScope": { ... }
}
}
}
```
This required a decent amount of custom converter code.
I'm very open for suggestions for how to do this better, but I've tried multiple approaches, and this gave the best results …

Groups support

---

CogniteSdk.Types/Common/Update.cs
CogniteSdk.Types/Files/FileCreate.cs
CogniteSdk.Types/Files/FileUpdate.cs
CogniteSdk/test/fsharp/TimeSeries.fs

Two small improvements to labels in the SDK:
- Files now have labels.
- Label updates have "Set". I couldn't find a better way to do this without it being a breaking change. At least nothing clean and obvious. This will work with any old code, and be functional for new code.

Labels improvements

---

CogniteSdk.Types/Groups/Acls.cs

This seems stupid, because one would expect Skip() to be `if (!TrySkip()) throw new JsonException()`, but it is _not_. In fact, Skip() fails immediately if the JSON is partial, TrySkip will try to parse the JSON. So if the payload is large enough, Skip() will fail and TrySkip() will not.
See https://github.com/dotnet/runtime/blob/64c05a3bcb4e71ee9972a3fb47eb4d3e061d3462/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs#L303

Use TrySkip instead of Skip

---

CogniteSdk.Types/Groups/Acls.cs
CogniteSdk/test/fsharp/Groups.fs

Turns out docs is wrong here, and there is probably something funky with how this is done in the auth API itself. IdScope is documented to be (mostly) arrays of integers, but they are generally universally arrays of strings, although the API accepts arrays of integers on groups create.
We solve this by just using integers locally (which is better for the user), and sending integers to the API (since it works, and is technically more compact). There is a convenient attribute in System.Text.Json which handles this for us.
I also added a few tests, to make sure this actually works.

Fix bug serializing ACLs with idscope

---

CogniteSdk.Types/Assets/AssetQuery.cs
CogniteSdk.Types/Common/IPartitionedQuery.cs
CogniteSdk.Types/Events/EventQuery.cs
CogniteSdk.Types/Timeseries/TimeSeriesQuery.cs

It is already possible to generalize methods which use ItemsWithCursor and CursorQueryBase. This makes it possible to generalize methods using partitions as well, reducing code duplication.

Add common interface for queries with partition

---

README.md

This is what was used to create the tool manifest that only needs to be done once:
```sh
> dotnet new tool-manifest
> dotnet tool install Paket
```
Updated instead with what a new dev onboarding into the project needs to know.

document dotnet tool install requirement

---

paket.dependencies
paket.lock

One of the System.Text.Json dependencies wasn't updated.
We also need to find a solution to conflicts created by FSharp.Core, though that requires a change to Oryx, I think.

Fix packet conflicts

---

CogniteSdk.Types/Alpha/Simulators/SimulationRunCreate.cs
CogniteSdk/src/Resources/Alpha/Simulators.cs
CogniteSdk/test/fsharp/Alpha/Simulators.fs
Oryx.Cognite/src/Alpha/Simulators.fs

- this is needed for the simulator connector to support scheduled runs
- changed method names to `...Async` to conform with other APIs

[Simulators API] add simulation run create

---

.github/workflows/build-and-test.yml
CogniteSdk/src/Client.cs
CogniteSdk/src/Resources/Annotations.cs
CogniteSdk/src/Resources/Playground.cs
CogniteSdk/test/csharp/Annotations.cs
Oryx.Cognite/src/Annotations.fs
Oryx.Cognite/src/Handler.fs
Oryx.Cognite/src/Oryx.Cognite.fsproj
Oryx.Cognite/src/Playground/Handler.fs
cognite-sdk-dotnet.sln

I tried to move the annotation API to the official version of the STK. But both build system and F# is unknown for me. So I will need some help to do this. I have tried to move the according fs files, but I got compiler errors.
I also miss the C# test in the solution file. Why isn't not included, so we can see the build is failing before pushing the code?

Move Annotation from Playground to the official part

---

.github/workflows/publish.yml

Should be the last one. The created tag was just "v" which is problematic. I fixed it manually for 3.12.0

Fix release and tag name

---

.github/workflows/publish.yml

Seems like github actions don't fetch tags by default. This is needed to prevent double release, which will only partially fail.

Fix release check

---

CogniteSdk.FSharp/src/DataPointAggregates.fs
CogniteSdk.FSharp/src/TimeSeries.fs
CogniteSdk.Types/DataPoints/DataPointsItem.cs
CogniteSdk.Types/DataPoints/DataPointsQuery.cs
CogniteSdk.Types/Timeseries/TimeSeries.cs
CogniteSdk.Types/Timeseries/TimeSeriesCreate.cs
CogniteSdk.Types/Timeseries/TimeSeriesFilter.cs
CogniteSdk.Types/Timeseries/TimeSeriesUpdate.cs
CogniteSdk/test/fsharp/DataPoints.fs
CogniteSdk/test/fsharp/TimeSeries.fs

This pull request includes updates to the TimeSeries and DataPoints classes. 
The changes include:
- New properties `TargetUnit` and `TargetUnitSystem` added to the `DataPointsQueryItem` class, allowing to fetch datapoints with unit conversion.
- New property `UnitExternalId` added to the `TimeSeries` classes, allowing to expose the new property on responses, creating and updating `TimeSeries` objects.
- New properties `UnitExternalId` and `UnitQuantity` added to the `TimeSeriesFilter` class, allowing to perform unit aware filtering queries to time series.

Add support for standardised units in timeseries

---

.github/workflows/publish.yml

Update version of the code-sign-action before upcoming signing key rotation.
Changes:
* Bump version of the code-sign-action.
* Add keypair alias variable which was hard coded in the previous versions.

[SEC-3551] Update version of the code-sign-action
